[build]
  publish = "build"
  command = "REACT_APP_CONTEXT=$CONTEXT npm run build"
[build.environment]
  REACT_APP_LISTING = "Hello"
  NODE_VERSION = "16.14.2"
  YARN_VERSION = "1.22.17"
  YARN_FLAGS = "--no-ignore-optional"


