[build]
  publish = "build"
  command = "react-scripts build"
[build.environment]
  REACT_APP_LISTING = "Hello"
  NODE_VERSION = "16.14.2"
  YARN_VERSION = "1.22.17"
  YARN_FLAGS = "--no-ignore-optional"


